# Generated by Django 4.2 on 2023-05-12 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calories",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Total Fat (g)",
                    ),
                ),
                (
                    "saturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "polyunsaturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "monosaturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "trans_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Total Carbs (g)",
                    ),
                ),
                (
                    "fiber_carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "sugar_carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "potassium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "vitamin_a_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "vitamin_c_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "calcium_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "iron_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FoodProduct",
            fields=[
                (
                    "food_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="foods.food",
                    ),
                ),
                ("serving_size", models.PositiveIntegerField(default=100)),
                (
                    "serving_unit",
                    models.CharField(
                        choices=[("g", "gram(s)"), ("mg", "miligram(s)")],
                        default="g",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "barcode",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("brand", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("foods.food", models.Model),
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "food_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="foods.food",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("number_of_servings", models.PositiveIntegerField()),
                ("link", models.URLField(blank=True)),
                (
                    "nutrients_from_ingredients",
                    models.BooleanField(
                        default=False,
                        verbose_name="Calculate nutrients from ingredients",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("foods.food",),
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calories",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Total Fat (g)",
                    ),
                ),
                (
                    "saturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "polyunsaturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "monosaturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "trans_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Total Carbs (g)",
                    ),
                ),
                (
                    "fiber_carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "sugar_carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "potassium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "vitamin_a_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "vitamin_c_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "calcium_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "iron_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("serving_size", models.PositiveIntegerField(default=100)),
                (
                    "serving_unit",
                    models.CharField(
                        choices=[("g", "gram(s)"), ("mg", "miligram(s)")],
                        default="g",
                        max_length=20,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="foods.foodproduct",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="foods.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
