# Generated by Django 4.1.5 on 2023-01-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "calories",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "protein_grs",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "fat_grs",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Total Fat (gr)",
                    ),
                ),
                (
                    "saturated_fat_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "polyunsaturated_fat_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "monosaturated_fat_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "trans_fat_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "carbs_grs",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Total Carbs (gr)",
                    ),
                ),
                (
                    "fiber_carbs_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "sugar_carbs_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "sodium_mgrs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "potassium_mgrs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "vitamin_a_perc",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "vitamin_c_perc",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "calcium_perc",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "iron_perc",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                ("brand", models.CharField(max_length=255)),
                ("serving_size", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "calories",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "protein_grs",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "fat_grs",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Total Fat (gr)",
                    ),
                ),
                (
                    "saturated_fat_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "polyunsaturated_fat_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "monosaturated_fat_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "trans_fat_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "carbs_grs",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Total Carbs (gr)",
                    ),
                ),
                (
                    "fiber_carbs_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "sugar_carbs_grs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "sodium_mgrs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "potassium_mgrs",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "vitamin_a_perc",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "vitamin_c_perc",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "calcium_perc",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "iron_perc",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                ("description", models.TextField(blank=True)),
                ("number_of_servings", models.PositiveIntegerField()),
                ("link", models.URLField(blank=True)),
                (
                    "macros_from_ingredients",
                    models.BooleanField(
                        default=False,
                        verbose_name="Calculate macros from ingredients",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "servings",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="foods.food",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="foods.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
