# Generated by Django 4.2 on 2023-06-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="serving_size",
            new_name="nutritional_info_size",
        ),
        migrations.RemoveField(
            model_name="food",
            name="serving_unit",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="serving_size",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="serving_unit",
        ),
        migrations.AddField(
            model_name="food",
            name="nutritional_info_unit",
            field=models.CharField(
                choices=[
                    ("g", "gram(s)"),
                    ("mg", "miligram(s)"),
                    ("l", "litre(s)"),
                    ("ml", "millilitre(s)"),
                    ("unit", "unit(s)"),
                    ("cup", "cup(s)"),
                    ("serving", "serving(s)"),
                    ("container", "container(s)"),
                ],
                default="g",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="weight",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="food",
            name="weight_unit",
            field=models.CharField(
                choices=[
                    ("g", "gram(s)"),
                    ("mg", "miligram(s)"),
                    ("l", "litre(s)"),
                    ("ml", "millilitre(s)"),
                    ("unit", "unit(s)"),
                    ("cup", "cup(s)"),
                    ("serving", "serving(s)"),
                    ("container", "container(s)"),
                ],
                default="g",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="num_servings",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="foodproduct",
            name="barcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Serving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=10
                    ),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Fat (g)",
                    ),
                ),
                (
                    "saturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "polyunsaturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "monosaturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "trans_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Carbs (g)",
                    ),
                ),
                (
                    "fiber_carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "sugar_carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "potassium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "vitamin_a_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "vitamin_c_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "calcium_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "iron_perc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("size", models.PositiveIntegerField(default=100)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "gram(s)"),
                            ("mg", "miligram(s)"),
                            ("l", "litre(s)"),
                            ("ml", "millilitre(s)"),
                            ("unit", "unit(s)"),
                            ("cup", "cup(s)"),
                            ("serving", "serving(s)"),
                            ("container", "container(s)"),
                        ],
                        default="g",
                        max_length=20,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servings",
                        to="foods.food",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="foods.serving",
            ),
        ),
    ]
