# Generated by Django 4.1.5 on 2023-01-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="barcode",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
