# Generated by Django 4.2 on 2023-05-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0002_alter_food_calories_alter_food_carbs_g_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodproduct",
            name="name",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="name",
        ),
        migrations.AddField(
            model_name="food",
            name="name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
    ]
