# Generated by Django 4.2 on 2023-06-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0003_remove_foodproduct_name_remove_recipe_name_food_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodproduct",
            name="serving_size",
        ),
        migrations.RemoveField(
            model_name="foodproduct",
            name="serving_unit",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="number_of_servings",
        ),
        migrations.AddField(
            model_name="food",
            name="serving_size",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="food",
            name="serving_unit",
            field=models.CharField(
                choices=[("g", "gram(s)"), ("mg", "miligram(s)")],
                default="g",
                max_length=20,
            ),
        ),
    ]
