# Generated by Django 4.1.5 on 2023-01-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0003_rename_carbs_grs_food_carbs_g_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="calcium_perc",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=1, max_digits=10, verbose_name="Total Carbs (g)"
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=1, max_digits=10, verbose_name="Total Fat (g)"
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="fiber_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="iron_perc",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="monosaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="polyunsaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="potassium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="saturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="serving_size",
            field=models.CharField(default=100, max_length=255),
        ),
        migrations.AlterField(
            model_name="food",
            name="sodium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="sugar_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="trans_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="vitamin_a_perc",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="vitamin_c_perc",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="calcium_perc",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=1, max_digits=10, verbose_name="Total Carbs (g)"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=1, max_digits=10, verbose_name="Total Fat (g)"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="fiber_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="iron_perc",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="monosaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="polyunsaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="potassium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="saturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="sodium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="sugar_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="trans_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="vitamin_a_perc",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="vitamin_c_perc",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
