# Generated by Django 4.1.5 on 2023-01-14 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0004_alter_food_calcium_perc_alter_food_carbs_g_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="serving_size",
        ),
        migrations.RemoveField(
            model_name="food",
            name="serving_unit",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="servings",
        ),
    ]
