# Generated by Django 4.2 on 2023-06-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0004_food_num_servings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="num_servings",
            field=models.DecimalField(
                decimal_places=1, default=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="num_servings",
            field=models.DecimalField(
                decimal_places=1, default=1, max_digits=10
            ),
        ),
    ]
