# Generated by Django 4.2 on 2023-06-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0005_alter_food_serving_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="link",
        ),
        migrations.AddField(
            model_name="food",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
