# Generated by Django 4.1.5 on 2023-01-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "foods",
            "0005_remove_food_serving_size_remove_food_serving_unit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="calcium_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="iron_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="vitamin_a_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="vitamin_c_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="calcium_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="iron_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="vitamin_a_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="vitamin_c_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
