# Generated by Django 4.2.4 on 2023-08-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0005_alter_food_num_servings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="protein_g",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Protein (g)",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="protein_g",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Protein (g)",
            ),
        ),
        migrations.AlterField(
            model_name="serving",
            name="protein_g",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Protein (g)",
            ),
        ),
    ]
