# Generated by Django 4.1.5 on 2023-01-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "foods",
            "0006_alter_food_calcium_perc_alter_food_iron_perc_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="fiber_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="monosaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="polyunsaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="potassium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="saturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="sodium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="sugar_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="trans_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="fiber_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="monosaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="polyunsaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="potassium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="saturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="sodium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="sugar_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="trans_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
    ]
