# Generated by Django 4.2 on 2023-06-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0006_remove_recipe_link_food_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="serving_unit",
            field=models.CharField(
                choices=[
                    ("g", "gram(s)"),
                    ("mg", "miligram(s)"),
                    ("serving", "serving(s)"),
                ],
                default="g",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="serving_unit",
            field=models.CharField(
                choices=[
                    ("g", "gram(s)"),
                    ("mg", "miligram(s)"),
                    ("serving", "serving(s)"),
                ],
                default="g",
                max_length=20,
            ),
        ),
    ]
