# Generated by Django 4.2.4 on 2023-11-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0006_alter_food_protein_g_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodproduct",
            name="barcode",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
