# Generated by Django 4.2.4 on 2023-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0007_alter_foodproduct_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="weight",
            field=models.DecimalField(
                decimal_places=1, default=100, max_digits=10
            ),
        ),
    ]
