# Generated by Django 4.2 on 2023-06-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0008_alter_food_serving_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodproduct",
            name="brand",
        ),
        migrations.AddField(
            model_name="food",
            name="brand",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
