# Generated by Django 4.1.5 on 2023-01-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0008_food_serving_size_food_serving_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="serving_size",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="serving_size",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
