# Generated by Django 4.1.5 on 2023-01-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0009_alter_food_serving_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="calories",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="carbs_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=10,
                null=True,
                verbose_name="Total Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="fat_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=10,
                null=True,
                verbose_name="Total Fat (g)",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="protein_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
    ]
