# Generated by Django 4.1.5 on 2023-01-15 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0011_recipeingredient_calcium_perc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="ingredient",
            new_name="food",
        ),
    ]
