# Generated by Django 4.1.5 on 2023-01-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0012_rename_ingredient_recipeingredient_food"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="macros_from_ingredients",
        ),
        migrations.AddField(
            model_name="recipe",
            name="nutrients_from_ingredients",
            field=models.BooleanField(
                default=False,
                verbose_name="Calculate nutrients from ingredients",
            ),
        ),
    ]
