version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "daily"
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
  - package-ecosystem: "docker"
    directory: "/backend/platform/docker/"
    schedule:
      interval: "daily"
    groups:
      updates:
        patterns:
          - "*"
