version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "backend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "node"
    directory: "webapp/"
    schedule:
      interval: "daily"
