# Generated by Django 5.2.15 on 2026-07-31 23:04

import apps.health_sync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthsyncdevice",
            name="expires_at",
            field=models.DateTimeField(
                default=apps.health_sync.models.device_token_expiry
            ),
        ),
        migrations.AddField(
            model_name="healthsyncdevice",
            name="last_success_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
