# Generated by Django 5.2.15 on 2026-07-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_sync", "0002_healthsyncdevice_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepimport",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
