# Generated by Django 5.2.17 on 2026-08-22 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_watermarks(apps, schema_editor):
    """Retain the newest imported observation for each owner and date."""
    step_import = apps.get_model("health_sync", "StepImport")
    watermark = apps.get_model("health_sync", "StepSyncWatermark")
    using = schema_editor.connection.alias
    imports = step_import.objects.using(using).values(
        "day_steps__day__plan__user_id",
        "day_steps__day__day",
        "observed_at",
    )
    for item in imports.iterator():
        row, created = watermark.objects.using(using).get_or_create(
            user_id=item["day_steps__day__plan__user_id"],
            date=item["day_steps__day__day"],
            defaults={"observed_at": item["observed_at"]},
        )
        if not created and item["observed_at"] > row.observed_at:
            row.observed_at = item["observed_at"]
            row.save(using=using, update_fields=["observed_at", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("health_sync", "0003_stepimport_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StepSyncWatermark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("observed_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_sync_watermarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"),
                        name="unique_step_sync_watermark_per_user_date",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_watermarks, migrations.RunPython.noop),
    ]
