# Generated by Django 5.2.17 on 2026-09-02 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_alter_exercise_duration"),
        ("health_sync", "0004_stepsyncwatermark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        default="garmin_health_connect", max_length=32
                    ),
                ),
                ("source_record_id", models.CharField(max_length=255)),
                ("source_modified_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_imports",
                        to="health_sync.healthsyncdevice",
                    ),
                ),
                (
                    "exercise",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_import",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "source_modified_at"],
                        name="health_sync_user_id_aa7c1f_idx",
                    ),
                    models.Index(
                        fields=["source", "is_active"],
                        name="health_sync_source_ace8ad_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source_record_id"),
                        name="unique_activity_import_per_user_record",
                    )
                ],
            },
        ),
    ]
