# Generated by Django 5.2.17 on 2026-10-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_sync", "0004_stepsyncwatermark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthSyncAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("challenge", models.CharField(max_length=43)),
                ("redirect_uri", models.CharField(max_length=120)),
                ("issuer", models.CharField(max_length=255)),
                ("device_name", models.CharField(max_length=120)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthSyncGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_expires_at", models.DateTimeField()),
                ("refresh_hash", models.CharField(max_length=64, unique=True)),
                (
                    "previous_refresh_hash",
                    models.CharField(blank=True, max_length=64),
                ),
                ("issuer", models.CharField(max_length=255)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_grant",
                        to="health_sync.healthsyncdevice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
