# Generated by Django 5.2.17 on 2026-10-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_sync", "0005_healthsyncauthorization_healthsyncgrant"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthSyncSpentRefresh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spent_refreshes",
                        to="health_sync.healthsyncgrant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grant", "token_hash"),
                        name="unique_spent_refresh_per_grant",
                    )
                ],
            },
        ),
    ]
