# Generated by Django 5.2.17 on 2026-10-08 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_sync", "0006_healthsyncspentrefresh"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthSyncRefreshClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_claims",
                        to="health_sync.healthsyncdevice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
