# Generated by Django 4.2 on 2023-06-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "foods",
            "0002_rename_serving_size_food_nutritional_info_size_and_more",
        ),
        ("plans", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intake",
            name="serving_size",
        ),
        migrations.RemoveField(
            model_name="intake",
            name="serving_unit",
        ),
        migrations.AddField(
            model_name="intake",
            name="num_servings",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="intake",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foods.serving"
            ),
        ),
    ]
