# Generated by Django 4.2 on 2023-06-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0003_remove_intake_serving_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="intake",
            name="calories",
        ),
        migrations.AddField(
            model_name="day",
            name="energy",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Energy (kcal)",
            ),
        ),
        migrations.AddField(
            model_name="intake",
            name="energy",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Energy (kcal)",
            ),
        ),
    ]
