# Generated by Django 5.1 on 2024-08-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_alter_day_calorie_intake_perc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="salt_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="intake",
            name="salt_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
    ]
