# Generated by Django 5.1 on 2024-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0007_day_salt_g_intake_salt_g"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="fiber_carbs_g",
            new_name="fibre_carbs_g",
        ),
        migrations.RenameField(
            model_name="intake",
            old_name="fiber_carbs_g",
            new_name="fibre_carbs_g",
        ),
    ]
