# Generated by Django 5.1.3 on 2024-11-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0008_rename_fiber_carbs_g_day_fibre_carbs_g_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weekplan",
            name="fat_perc",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Fat percentage of the total calorie goal. The recommended value is 15-25% for cutting and 20-30% for bulking.",
                max_digits=10,
                verbose_name="Fat (%)",
            ),
        ),
        migrations.AlterField(
            model_name="weekplan",
            name="protein_g_kg",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Protein grams consumed per kilo of body weight. The recommended value is 2.3-2.8g/kg for cutting and 1.8-2.2g/kg for bulking.",
                max_digits=10,
                verbose_name="Protein (g/kg)",
            ),
        ),
    ]
