# Generated by Django 5.1.3 on 2024-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0009_alter_weekplan_fat_perc_alter_weekplan_protein_g_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="calcium_perc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="calorie_goal",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="calorie_intake_perc",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Calorie Intake %",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="carbs_g_goal",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="carbs_g_intake_perc",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Carbs Intake %",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="energy",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Energy (kcal)",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Fat (g)",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="fat_g_goal",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="fat_g_intake_perc",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Fat Intake %",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="fibre_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="iron_perc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="monosaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="polyunsaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="potassium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="protein_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Protein (g)",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="protein_g_goal",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="protein_g_intake_perc",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Protein Intake %",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="salt_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="saturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="sodium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="sugar_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="trans_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="vitamin_a_perc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="vitamin_c_perc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="calcium_perc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="energy",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Energy (kcal)",
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Fat (g)",
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="fibre_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="iron_perc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="monosaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="polyunsaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="potassium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="protein_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Protein (g)",
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="salt_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="saturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="sodium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="sugar_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="trans_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="vitamin_a_perc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="vitamin_c_perc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
