# Generated by Django 5.1.3 on 2024-11-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plans",
            "0010_alter_day_calcium_perc_alter_day_calorie_goal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="intake",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
