# Generated by Django 5.1.3 on 2024-11-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0011_intake_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="intake",
            name="processed",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the intake's notes have been processed.",
            ),
        ),
    ]
