# Generated by Django 5.1.3 on 2024-11-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0012_intake_processed"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("picture", models.ImageField(upload_to="intake_pictures")),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="plans.intake",
                    ),
                ),
            ],
        ),
    ]
