# Generated by Django 5.1.3 on 2024-12-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0014_alter_intake_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intakes",
                to="plans.day",
            ),
        ),
    ]
