# Generated by Django 5.1.3 on 2024-12-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0018_alter_intake_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="processed",
            field=models.BooleanField(
                default=True,
                editable=False,
                help_text="Indicates whether the intake's notes have been processed.",
            ),
        ),
    ]
