# Generated by Django 5.1.3 on 2024-12-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0019_alter_intake_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="breakfast",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether breakfast was logged. Unprocessed breakfast won't count as logged.",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="dinner",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether dinner was logged. Unprocessed dinner won't count as logged.",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="exercises_flag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether exercise was logged.",
                verbose_name="Exercises",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="lunch",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether lunch was logged. Unprocessed lunch won't count as logged.",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="steps_flag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether steps were logged.",
                verbose_name="Steps",
            ),
        ),
    ]
