# Generated by Django 5.1.3 on 2024-12-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0020_day_breakfast_day_dinner_day_exercises_flag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="breakfast",
            new_name="breakfast_flag",
        ),
        migrations.RenameField(
            model_name="day",
            old_name="dinner",
            new_name="dinner_flag",
        ),
        migrations.RenameField(
            model_name="day",
            old_name="lunch",
            new_name="lunch_flag",
        ),
        migrations.AddField(
            model_name="day",
            name="breakfast_exc",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether breakfast is exceptionally not logged.",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="dinner_exc",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether dinner is exceptionally not logged.",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="excercises_exc",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether exercises are exceptionally not logged.",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="lunch_exc",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether lunch is exceptionally not logged.",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="snack_exc",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether snacks are exceptionally not logged.",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="snack_flag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether snacks were logged. Unprocessed snacks won't count as logged.",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="steps_exc",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether steps are exceptionally not logged.",
            ),
        ),
    ]
