# Generated by Django 5.1.3 on 2024-12-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0021_rename_breakfast_day_breakfast_flag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="excercises_exc",
            new_name="exercises_exc",
        ),
        migrations.AlterField(
            model_name="day",
            name="breakfast_flag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether breakfast was logged. Unprocessed breakfast won't count as logged.",
                verbose_name="Breakfast",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="dinner_flag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether dinner was logged. Unprocessed dinner won't count as logged.",
                verbose_name="Dinner",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="lunch_flag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether lunch was logged. Unprocessed lunch won't count as logged.",
                verbose_name="Lunch",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="snack_flag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether snacks were logged. Unprocessed snacks won't count as logged.",
                verbose_name="Snacks",
            ),
        ),
    ]
