# Generated by Django 5.1.4 on 2025-01-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0024_weekplan_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={"ordering": ["-plan", "-day"]},
        ),
    ]
