# Generated by Django 5.1.4 on 2025-01-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0025_alter_day_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="energy",
            new_name="energy_kcal",
        ),
        migrations.RenameField(
            model_name="intake",
            old_name="energy",
            new_name="energy_kcal",
        ),
    ]
