# Generated by Django 5.1.4 on 2025-01-25 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0002_initial"),
        ("plans", "0026_rename_energy_day_energy_kcal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="calorie_goal",
            new_name="energy_goal",
        ),
        migrations.RenameField(
            model_name="day",
            old_name="calorie_intake_perc",
            new_name="energy_intake_perc",
        ),
    ]
