# Generated by Django 5.1.4 on 2025-01-25 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0002_initial"),
        ("plans", "0027_rename_calorie_goal_day_energy_goal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="energy_intake_perc",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Energy Intake %",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="tracked",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the day's intakes and exercises are taken into account for the energy intake and goal, respectively. Otherwise, the estimated values are used. This field is toggled to true as soon as an exercise or an intake is logged.",
            ),
        ),
        migrations.AlterField(
            model_name="weekplan",
            name="fat_perc",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Fat percentage of the total energy goal. The recommended value is 15-25% for cutting and 20-30% for bulking.",
                max_digits=10,
                verbose_name="Fat (%)",
            ),
        ),
        migrations.AlterField(
            model_name="weekplan",
            name="measurement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="week_plans",
                to="measurements.measurement",
            ),
        ),
        migrations.AlterField(
            model_name="weekplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="week_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
