# Generated by Django 5.1.4 on 2025-01-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "plans",
            "0028_alter_day_energy_intake_perc_alter_day_tracked_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="energy_goal",
            new_name="energy_kcal_goal",
        ),
        migrations.RenameField(
            model_name="day",
            old_name="energy_intake_perc",
            new_name="energy_kcal_intake_perc",
        ),
    ]
