# Generated by Django 5.1.6 on 2025-02-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0029_rename_energy_goal_day_energy_kcal_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="abv_perc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Alcohol by volume (%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="intake",
            name="abv_perc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Alcohol by volume (%)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
