# Generated by Django 5.1.6 on 2025-03-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0031_alter_intake_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="carbs_g_goal",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Carbs (g) Goal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="energy_kcal_goal",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Energy (kcal) Goal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Fat (g)",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="fat_g_goal",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Fat (g) Goal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="protein_g_goal",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Protein (g) Goal",
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Fat (g)",
            ),
        ),
    ]
