# Generated by Django 5.2.17 on 2026-09-11 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "measurements",
            "0004_measurement_body_fat_calculation_perc_and_more",
        ),
        ("plans", "0032_alter_day_carbs_g_alter_day_carbs_g_goal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="day",
            constraint=models.UniqueConstraint(
                fields=("plan", "day"), name="unique_plan_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="day",
            constraint=models.UniqueConstraint(
                fields=("plan", "day_num"), name="unique_plan_day_num"
            ),
        ),
        migrations.AddConstraint(
            model_name="weekplan",
            constraint=models.UniqueConstraint(
                fields=("user", "start_date"), name="unique_user_week_start"
            ),
        ),
    ]
