# Generated by Django 5.2.15 on 2026-08-02 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["user", "-created_at", "-id"],
                name="measurement_latest_idx",
            ),
        ),
    ]
