# Generated by Django 5.2.16 on 2026-08-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0003_add_latest_measurement_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="body_fat_calculation_perc",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                editable=False,
                max_digits=10,
                null=True,
                verbose_name="Body fat used for calculations (%)",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="body_fat_perc",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=10,
                null=True,
                verbose_name="Body fat (%)",
            ),
        ),
    ]
