# Generated by Django 4.2 on 2023-06-23 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DaySteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("steps", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Day steps",
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time", models.TimeField(default=datetime.time(0, 0))),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("walk", "Walk"),
                            ("run", "Run"),
                            ("cycle", "Cycle"),
                            ("gym", "Gym"),
                        ],
                        max_length=20,
                    ),
                ),
                ("kcals", models.PositiveIntegerField()),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distance (km)",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
