# Generated by Django 5.1.3 on 2024-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="duration",
            field=models.DurationField(
                blank=True, help_text="hh:mm:ss", null=True
            ),
        ),
    ]
