version: 2.1

executors:
  api:
    docker:
      - image: "python:3.11.3-slim-bullseye"
    environment:
      PATH: "/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin"
  webapp:
    docker:
      - image: "node:lts-alpine3.17"

commands:
  validate-api:
    parameters:
      env:
        type: string
      poetry-version:
        default: "1.3.2"
        type: string
    steps:
      - checkout:
          path: ~/project

      # Poetry
      - restore_cache:
          name: Restore Poetry
          keys:
            - poetry-<<parameters.poetry-version>>-v1
      - run:
          name: Install Poetry
          command: pip install --user poetry==<<parameters.poetry-version>>
      - save_cache:
          name: Cache Poetry
          key: poetry-<<parameters.poetry-version>>-v1
          paths:
            - /root/.local/

      # API dependencies
      - restore_cache:
          name: Restore API Dependencies
          keys:
            - api-packages-{{ checksum "poetry.lock" }}-v1
      - run:
          name: Install API Dependencies
          command: poetry install --no-ansi
      - save_cache:
          name: Save API Dependencies
          key: api-packages-{{ checksum "poetry.lock" }}-v1
          paths:
            - /root/.cache/pypoetry/

      # Tox
      - restore_cache:
          name: Restore Tox Dependencies
          keys:
            - tox-<<parameters.env>>-{{ checksum "poetry.lock" }}-v1
      - run:
          name: <<parameters.env>>
          command: poetry run tox -e <<parameters.env>>
      - save_cache:
          name: Save Tox Dependencies
          key: tox-<<parameters.env>>-{{ checksum "poetry.lock" }}-v1
          paths:
            - .tox/<<parameters.env>>/lib

  validate-webapp:
    parameters:
      env:
        type: string
    steps:
      - checkout:
          path: ~/project

      # Webapp dependencies
      - restore_cache:
          name: Restore Webapp dependencies
          keys:
            - webapp-packages-{{ checksum "yarn.lock" }}-v1
      - run:
          name: Install Webapp dependencies
          command: yarn install
      - save_cache:
          name: Save Webapp Dependencies
          key: webapp-packages-{{ checksum "yarn.lock" }}-v1
          paths:
            - node_modules

      # Run chekcers
      - run:
          name: <<parameters.env>>
          command: yarn <<parameters.env>>

jobs:
  api-pytest:
    working_directory: ~/project/api
    executor: api
    steps:
      - validate-api:
          env: pytest
  api-bandit:
    working_directory: ~/project/api
    executor: python
    steps:
      - validate:
          env: bandit
  api-flake8:
    working_directory: ~/project/api
    executor: api
    steps:
      - validate-api:
          env: flake8
  api-black:
    working_directory: ~/project/api
    executor: api
    steps:
      - validate-api:
          env: black
  api-mypy:
    working_directory: ~/project/api
    executor: api
    steps:
      - validate-api:
          env: mypy
  api-pylint:
    working_directory: ~/project/api
    executor: api
    steps:
      - validate-api:
          env: pylint
  api-pylint-tests:
    working_directory: ~/project/api
    executor: api
    steps:
      - validate-api:
          env: pylint-tests
  api-pydocstyle:
    working_directory: ~/project/api
    executor: api
    steps:
      - validate-api:
          env: pydocstyle
  api-pydocstyle-tests:
    working_directory: ~/project/api
    executor: api
    steps:
      - validate-api:
          env: pydocstyle-tests
  webapp-build-lint:
    working_directory: ~/project/webapp
    executor: webapp
    steps:
      - validate-webapp:
          env: build
  webapp-test-coverage:
    working_directory: ~/project/webapp
    executor: webapp
    steps:
      - validate-webapp:
          env: test:ci
  webapp-cpd:
    working_directory: ~/project/webapp
    executor: webapp
    steps:
      - validate-webapp:
          env: cpd

workflows:
  version: 2
  ValidationWorkflow:
    jobs:
      - api-pytest
      - api-bandit
      - api-flake8
      - api-black
      - api-mypy
      - api-pylint
      - api-pylint-tests
      - api-pydocstyle
      - api-pydocstyle-tests
      - webapp-build-lint
      - webapp-test-coverage
      - webapp-cpd
