# Generated by Django 4.1.5 on 2023-01-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("measurements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("snack", "Snack"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meal_order", models.PositiveIntegerField(editable=False)),
                (
                    "servings",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DayTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField()),
            ],
            options={
                "ordering": ["plan", "-day"],
            },
        ),
        migrations.CreateModel(
            name="WeekPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                (
                    "protein_kg",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Protein / kg (gr)",
                        max_digits=10,
                    ),
                ),
                (
                    "fat_perc",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "protein_goal_grs_day",
                    models.DecimalField(
                        decimal_places=1, editable=False, max_digits=10
                    ),
                ),
                (
                    "fat_goal_grs_day",
                    models.DecimalField(
                        decimal_places=1, editable=False, max_digits=10
                    ),
                ),
                (
                    "carbs_goal_grs_day",
                    models.DecimalField(
                        decimal_places=1, editable=False, max_digits=10
                    ),
                ),
                (
                    "protein_goal_grs_week",
                    models.DecimalField(
                        decimal_places=1, editable=False, max_digits=10
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calorie_plans",
                        to="measurements.measurement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
