# Generated by Django 4.1.5 on 2023-01-14 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weekplan",
            old_name="carbs_goal_grs_day",
            new_name="carbs_goal_g_day",
        ),
        migrations.RenameField(
            model_name="weekplan",
            old_name="fat_goal_grs_day",
            new_name="fat_goal_g_day",
        ),
        migrations.RenameField(
            model_name="weekplan",
            old_name="protein_goal_grs_day",
            new_name="protein_goal_g_day",
        ),
        migrations.RenameField(
            model_name="weekplan",
            old_name="protein_goal_grs_week",
            new_name="protein_goal_g_week",
        ),
    ]
