# Generated by Django 4.2 on 2023-05-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="calories",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Total Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Total Fat (g)",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="protein_g",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="calories",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Total Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Total Fat (g)",
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="protein_g",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=10
            ),
        ),
    ]
