# Generated by Django 4.2 on 2023-05-12 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plans",
            "0003_alter_day_calories_alter_day_carbs_g_alter_day_fat_g_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="intake",
            old_name="time",
            new_name="planned_time",
        ),
    ]
