# Generated by Django 4.1.5 on 2023-01-14 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plans",
            "0003_rename_carbs_goal_grs_day_weekplan_carbs_goal_g_day_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="weekplan",
            old_name="carbs_goal_g_day",
            new_name="carbs_g_goal_day",
        ),
        migrations.RenameField(
            model_name="weekplan",
            old_name="fat_goal_g_day",
            new_name="fat_g_goal_day",
        ),
        migrations.RenameField(
            model_name="weekplan",
            old_name="protein_goal_g_day",
            new_name="protein_g_goal_day",
        ),
        migrations.RenameField(
            model_name="weekplan",
            old_name="protein_goal_g_week",
            new_name="protein_g_goal_week",
        ),
    ]
