# Generated by Django 4.2 on 2023-05-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0004_rename_time_intake_planned_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weekplan",
            name="carbs_g_goal_day",
        ),
        migrations.RemoveField(
            model_name="weekplan",
            name="fat_g_goal_day",
        ),
        migrations.RemoveField(
            model_name="weekplan",
            name="fat_perc",
        ),
        migrations.RemoveField(
            model_name="weekplan",
            name="protein_g_goal_day",
        ),
        migrations.RemoveField(
            model_name="weekplan",
            name="protein_g_goal_week",
        ),
        migrations.RemoveField(
            model_name="weekplan",
            name="protein_kg",
        ),
        migrations.AddField(
            model_name="day",
            name="day_num",
            field=models.PositiveIntegerField(
                default=0, help_text="Day in the plan."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="day",
            name="deficit",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Deficit (kcals)"
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="tracked",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the day's intakes and exercises are taken into account for the calorie intake and goal, respectively. Otherwise, the estimated values are used. This field is toggled to true as soon as an exercise or an intake is logged.",
            ),
        ),
        migrations.AlterField(
            model_name="weekplan",
            name="deficit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="This deficit is the average per day. It might be different on each day of the week if the distribution is not even.",
                verbose_name="Deficit (kcals/day)",
            ),
        ),
        migrations.AlterField(
            model_name="weekplan",
            name="start_date",
            field=models.DateField(
                help_text="This field should not be changed after creation. Dependant fields and objects won't be recalculated."
            ),
        ),
    ]
