# Generated by Django 4.1.5 on 2023-01-14 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plans",
            "0004_rename_carbs_goal_g_day_weekplan_carbs_g_goal_day_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dayfood",
            name="servings",
        ),
    ]
