# Generated by Django 4.1.5 on 2023-01-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0005_remove_dayfood_servings"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayfood",
            name="serving_size",
            field=models.PositiveIntegerField(default=100, max_length=255),
        ),
        migrations.AddField(
            model_name="dayfood",
            name="serving_unit",
            field=models.CharField(
                choices=[("g", "gram(s)"), ("mg", "miligram(s)")],
                default="g",
                max_length=20,
            ),
        ),
    ]
