# Generated by Django 4.2.4 on 2023-08-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0005_alter_intake_num_servings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="calorie_intake_perc",
            field=models.DecimalField(
                decimal_places=1,
                editable=False,
                max_digits=10,
                verbose_name="Calorie Intake %",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="carbs_g_intake_perc",
            field=models.DecimalField(
                decimal_places=1,
                editable=False,
                max_digits=10,
                verbose_name="Carbs Intake %",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="fat_g_intake_perc",
            field=models.DecimalField(
                decimal_places=1,
                editable=False,
                max_digits=10,
                verbose_name="Fat Intake %",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="protein_g",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Protein (g)",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="protein_g_intake_perc",
            field=models.DecimalField(
                decimal_places=1,
                editable=False,
                max_digits=10,
                verbose_name="Protein Intake %",
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="protein_g",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Protein (g)",
            ),
        ),
    ]
