# Generated by Django 4.2 on 2023-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0005_remove_weekplan_carbs_g_goal_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weekplan",
            name="protein_g_kg",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Protein grams consumed per kilo of body weight",
                max_digits=10,
                verbose_name="Protein (g/kg)",
            ),
            preserve_default=False,
        ),
    ]
