# Generated by Django 4.1.5 on 2023-01-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0006_dayfood_serving_size_dayfood_serving_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayfood",
            name="serving_size",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
