# Generated by Django 4.2 on 2023-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0006_weekplan_protein_g_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="protein_g_goal",
            field=models.DecimalField(
                decimal_places=1, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
