# Generated by Django 4.2 on 2023-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0007_day_protein_g_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="weekplan",
            name="fat_perc",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
