# Generated by Django 4.2 on 2023-06-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0008_weekplan_fat_perc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weekplan",
            name="fat_perc",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Fat percentage of the total calorie goal.",
                max_digits=10,
                verbose_name="Fat (%)",
            ),
        ),
    ]
