# Generated by Django 4.1.5 on 2023-01-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0008_dayfood_calcium_perc_dayfood_calories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="daytracking",
            name="calcium_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="calories",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="carbs_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=10,
                null=True,
                verbose_name="Total Carbs (g)",
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="fat_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=10,
                null=True,
                verbose_name="Total Fat (g)",
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="fiber_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="iron_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="monosaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="polyunsaturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="potassium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="protein_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="saturated_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="sodium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="sugar_carbs_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="trans_fat_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="vitamin_a_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="daytracking",
            name="vitamin_c_perc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
