# Generated by Django 4.2 on 2023-05-06 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plans",
            "0009_daytracking_calcium_perc_daytracking_calories_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dayfood",
            name="time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
