# Generated by Django 4.2 on 2023-06-11 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0009_alter_weekplan_fat_perc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intake",
            name="planned_time",
        ),
    ]
