# Generated by Django 4.2 on 2023-06-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0010_remove_intake_planned_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="serving_unit",
            field=models.CharField(
                choices=[
                    ("g", "gram(s)"),
                    ("mg", "miligram(s)"),
                    ("u", "serving(s)"),
                ],
                default="g",
                max_length=20,
            ),
        ),
    ]
