# Generated by Django 4.2 on 2023-05-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0010_dayfood_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="weekplan",
            name="deficit",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Deficit (kcals/day)"
            ),
        ),
    ]
