# Generated by Django 4.2 on 2023-05-06 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0011_weekplan_deficit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dayfood",
            name="meal_order",
        ),
    ]
