# Generated by Django 4.2 on 2023-05-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0012_remove_dayfood_meal_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayfood",
            name="meal_order",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
