# Generated by Django 4.2 on 2023-06-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0013_alter_intake_serving_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="calorie_goal",
            field=models.DecimalField(
                decimal_places=1, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="day",
            name="calorie_intake_perc",
            field=models.DecimalField(
                decimal_places=1, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="day",
            name="carbs_g_goal",
            field=models.DecimalField(
                decimal_places=1, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="day",
            name="carbs_g_intake_perc",
            field=models.DecimalField(
                decimal_places=1, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="day",
            name="fat_g_goal",
            field=models.DecimalField(
                decimal_places=1, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="day",
            name="fat_g_intake_perc",
            field=models.DecimalField(
                decimal_places=1, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="day",
            name="protein_g_intake_perc",
            field=models.DecimalField(
                decimal_places=1, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
