# Generated by Django 4.2 on 2023-05-11 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0013_remove_recipe_macros_from_ingredients_and_more"),
        (
            "exercises",
            "0005_remove_daysteps_user_remove_exercise_date_time_and_more",
        ),
        ("plans", "0013_dayfood_meal_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DayTracking",
            new_name="Day",
        ),
        migrations.RenameModel(
            old_name="DayFood",
            new_name="Intake",
        ),
    ]
