# Generated by Django 4.2 on 2023-06-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0014_day_calorie_goal_day_calorie_intake_perc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="serving_unit",
            field=models.CharField(
                choices=[
                    ("g", "gram(s)"),
                    ("mg", "miligram(s)"),
                    ("serving", "serving(s)"),
                    ("cup", "cup(s)"),
                    ("ml", "millilitre(s)"),
                ],
                default="g",
                max_length=20,
            ),
        ),
    ]
