# Generated by Django 4.2 on 2023-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0015_alter_intake_serving_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={"ordering": ["-plan", "day"]},
        ),
        migrations.AlterField(
            model_name="day",
            name="deficit",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Planned deficit (kcals)"
            ),
        ),
    ]
