# Generated by Django 4.2 on 2023-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0016_alter_day_options_alter_day_deficit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="tracked",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the day's intakes and exercises are taken into account for the calorie intake and goal, respectively. Otherwise, the estimated values are used. This field is toggled to true as soon as an exercise or an intake is logged.",
            ),
        ),
    ]
