# Generated by Django 4.2 on 2023-06-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FatPercGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body_fat_perc",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
