# Generated by Django 5.1.3 on 2024-11-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatpercgoal",
            name="body_fat_perc",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Body fat percentage goal.",
                max_digits=10,
            ),
        ),
    ]
