# Generated by Django 4.2 on 2023-05-05 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="datetime",
            new_name="date_time",
        ),
    ]
