# Generated by Django 4.2 on 2023-05-12 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("plans", "0001_initial"),
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="plans.day",
            ),
        ),
        migrations.AddField(
            model_name="daysteps",
            name="day",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="plans.day",
            ),
        ),
    ]
