# Generated by Django 4.2 on 2023-06-17 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="daysteps",
            options={"verbose_name_plural": "Day steps"},
        ),
    ]
