# Generated by Django 4.2 on 2023-05-06 04:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0011_weekplan_deficit"),
        ("exercises", "0004_alter_exercise_type_daysteps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daysteps",
            name="user",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="user",
        ),
        migrations.AddField(
            model_name="exercise",
            name="day",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="plans.daytracking",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exercise",
            name="time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="daysteps",
            name="day",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="plans.daytracking",
            ),
        ),
    ]
