# Generated by Django 4.2 on 2023-06-11 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fatpercgoal",
            old_name="fat_perc",
            new_name="body_fat_perc",
        ),
    ]
