environments:
  default:
    values:
      - traefik.values.yaml

---

repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    chart: traefik/traefik
    namespace: traefik
    version: 26.0.0
    values:
      - certResolvers:
          letsencrypt:
            email: {{ .Values.email }}
            storage: /data/acme.json
            caserver: https://acme-v02.api.letsencrypt.org/directory
            httpchallenge:
              entrypoint: web

        logs:
          general:
            level: DEBUG
          access:
            enable: true

        providers: {{- toYaml $.Values.providers | nindent 10 }}


        ports:
          web:
            redirectTo:
              port: websecure

          websecure:
            tls:
              enabled: true
              certResolver: letsencrypt
              domains: {{- toYaml $.Values.domains | nindent 14 }}

        persistence:
          enabled: true

        deployment:
          initContainers:
            - name: volume-permissions
              image: busybox:1.31.1
              command: ["sh", "-c", "chmod -Rv 600 /data/* || true"]
              volumeMounts:
                - name: data
                  mountPath: /data
