releases:
- chart: ../../../backend/platform/kube
  name: backend
  namespace: nutrition-staging
  values:
  - env:
    - name: ALLOWED_HOSTS
      value: staging.nutfeex.ddns.net
    - name: ENVIRONMENT
      value: staging
    - name: GEMINI_API_KEY
      valueFrom:
        secretKeyRef:
          key: gemini-api-key
          name: nutrition-gemini-api-key
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: nutrition-postgresql
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: nutrition-django-secret-key
    - name: DEBUG
      value: 'True'
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        traefik.ingress.kubernetes.io/router.tls.domains.0.main: staging.nutfeex.ddns.net
      hosts:
      - host: staging.nutfeex.ddns.net
        paths:
        - path: /
          pathType: Prefix
  version: 0.15.0+build-5b1a60b-1730517455
