apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nutrition-preview-flux-test2
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform/k8s/overlays/staging
  prune: true
  wait: true
  timeout: 5m
  targetNamespace: nutrition-staging--flux-test2
  sourceRef:
    kind: GitRepository
    name: source-flux-test2
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  images:
    - name: luismunozvillarreal/nutrition-backend
      newTag: 87ad8629eacd929d20e7c4f07da74e63b3acb7c6
    - name: luismunozvillarreal/nutrition-webapp
      newTag: 87ad8629eacd929d20e7c4f07da74e63b3acb7c6
  patches:
    - patch: |
        - op: replace
          path: /spec/rules/0/host
          value: staging--flux-test2.${BASE_DOMAIN}
        - op: replace
          path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.tls.domains.0.main
          value: staging--flux-test2.${BASE_DOMAIN}
      target:
        kind: Ingress
        name: .*
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nutrition-backend
        spec:
          template:
            spec:
              containers:
                - name: backend
                  env:
                    - name: ALLOWED_HOSTS
                      value: "staging--flux-test2.${BASE_DOMAIN}"
                    - name: CSRF_TRUSTED_ORIGINS
                      value: "https://staging--flux-test2.${BASE_DOMAIN}"
      target:
        kind: Deployment
        name: nutrition-backend
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nutrition-webapp
        spec:
          template:
            spec:
              containers:
                - name: webapp
                  env:
                    - name: GRAPHQL_ENDPOINT
                      value: "https://staging--flux-test2.${BASE_DOMAIN}/graphql/"
                    - name: NEXTAUTH_URL
                      value: "https://staging--flux-test2.${BASE_DOMAIN}"
      target:
        kind: Deployment
        name: nutrition-webapp
