# Generated by Django 4.1.5 on 2023-01-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fat_perc",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
            ],
        ),
    ]
