# Generated by Django 4.2 on 2023-05-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="fat_perc",
        ),
        migrations.AddField(
            model_name="measurement",
            name="body_fat_perc",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Body fat (%)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="weight",
            field=models.DecimalField(
                decimal_places=1, max_digits=10, verbose_name="Weight (kg)"
            ),
        ),
    ]
