# Generated by Django 4.2 on 2023-06-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "foods",
            "0002_rename_serving_size_food_nutritional_info_size_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="serving",
            name="calories",
        ),
        migrations.AddField(
            model_name="food",
            name="energy",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Energy (kcal)",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="energy",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Energy (kcal)",
            ),
        ),
        migrations.AddField(
            model_name="serving",
            name="energy",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                verbose_name="Energy (kcal)",
            ),
        ),
    ]
