# Generated by Django 5.1 on 2024-08-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0006_alter_food_protein_g_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="salt_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="salt_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="serving",
            name="salt_g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
    ]
