# Generated by Django 5.0.7 on 2024-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0007_cupboarditem_cupboarditemserving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="weight",
            field=models.DecimalField(
                decimal_places=1, default=100, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="foodproduct",
            name="barcode",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
