# Generated by Django 5.1 on 2024-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0007_food_salt_g_recipeingredient_salt_g_serving_salt_g"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="fiber_carbs_g",
            new_name="fibre_carbs_g",
        ),
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="fiber_carbs_g",
            new_name="fibre_carbs_g",
        ),
        migrations.RenameField(
            model_name="serving",
            old_name="fiber_carbs_g",
            new_name="fibre_carbs_g",
        ),
    ]
