# Generated by Django 5.1 on 2024-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0008_rename_fiber_carbs_g_food_fibre_carbs_g_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodproduct",
            name="barcode",
            field=models.CharField(
                blank=True, default=0, max_length=255, null=True
            ),
        ),
    ]
