# Generated by Django 5.1 on 2024-08-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0009_alter_foodproduct_barcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CupboardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.BooleanField(default=False)),
                ("finished", models.BooleanField(default=False)),
                ("purchased_at", models.DateTimeField()),
                (
                    "consumed_perc",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cupboard_items",
                        to="foods.food",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CupboardItemServing",
            fields=[
                (
                    "serving_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="foods.serving",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servings",
                        to="foods.cupboarditem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("foods.serving",),
        ),
    ]
