# Generated by Django 5.1.2 on 2024-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0010_cupboarditem_cupboarditemserving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="weight",
            field=models.DecimalField(
                decimal_places=1, default=100, max_digits=10
            ),
        ),
    ]
