# Generated by Django 5.1.2 on 2024-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0010_cupboarditem_cupboarditemserving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="nutritional_info_unit",
            field=models.CharField(
                choices=[
                    ("kg", "kilogram(s)"),
                    ("g", "gram(s)"),
                    ("mg", "milligram(s)"),
                    ("oz", "ounce(s)"),
                    ("lb", "pound(s)"),
                    ("l", "litre(s)"),
                    ("ml", "millilitre(s)"),
                    ("tsp", "teaspoon(s)"),
                    ("tbsp", "tablespoon(s)"),
                    ("cup", "cup(s)"),
                    ("unit", "unit(s)"),
                    ("serving", "serving(s)"),
                    ("container", "container(s)"),
                ],
                default="g",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="weight_unit",
            field=models.CharField(
                choices=[
                    ("kg", "kilogram(s)"),
                    ("g", "gram(s)"),
                    ("mg", "milligram(s)"),
                    ("oz", "ounce(s)"),
                    ("lb", "pound(s)"),
                    ("l", "litre(s)"),
                    ("ml", "millilitre(s)"),
                    ("tsp", "teaspoon(s)"),
                    ("tbsp", "tablespoon(s)"),
                    ("cup", "cup(s)"),
                    ("unit", "unit(s)"),
                    ("serving", "serving(s)"),
                    ("container", "container(s)"),
                ],
                default="g",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="serving",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kilogram(s)"),
                    ("g", "gram(s)"),
                    ("mg", "milligram(s)"),
                    ("oz", "ounce(s)"),
                    ("lb", "pound(s)"),
                    ("l", "litre(s)"),
                    ("ml", "millilitre(s)"),
                    ("tsp", "teaspoon(s)"),
                    ("tbsp", "tablespoon(s)"),
                    ("cup", "cup(s)"),
                    ("unit", "unit(s)"),
                    ("serving", "serving(s)"),
                    ("container", "container(s)"),
                ],
                default="g",
                max_length=20,
            ),
        ),
    ]
