# Generated by Django 5.1.2 on 2024-11-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0011_alter_food_nutritional_info_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serving",
            name="size",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Size is the amount of units in the serving. For example, if the unit is grams and the size is 100, it means 100g. When the serving unit and the food weight unit is the same, then the weight of the serving is the same as the weight of the serving. However, when the unit of the serving is 'container' or 'serving', then the weight will most certainly differ from the size, e.g.: size 1 unit container weights 320g.",
            ),
        ),
    ]
