# Generated by Django 5.1.3 on 2024-11-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0013_alter_serving_size_cupboarditemconsumption_and_more"),
        ("plans", "0008_rename_fiber_carbs_g_day_fibre_carbs_g_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cupboarditemconsumption",
            name="num_servings",
        ),
        migrations.AddField(
            model_name="cupboarditemconsumption",
            name="intake",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cupboard_item_consumption",
                to="plans.intake",
            ),
        ),
    ]
