# Generated by Django 5.1.3 on 2024-11-18 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0014_remove_cupboarditemconsumption_num_servings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cupboarditemconsumption",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumptions",
                to="foods.cupboarditem",
            ),
        ),
    ]
