# Generated by Django 5.1.3 on 2024-11-23 23:49

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0016_alter_food_nutritional_info_unit_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
