# Generated by Django 5.1.4 on 2025-01-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0021_alter_food_nutritional_info_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="energy",
            new_name="energy_kcal",
        ),
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="energy",
            new_name="energy_kcal",
        ),
        migrations.RenameField(
            model_name="serving",
            old_name="energy",
            new_name="energy_kcal",
        ),
    ]
