# Generated by Django 5.1.6 on 2025-02-08 19:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0022_rename_energy_food_energy_kcal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="nutritional_info_size",
            field=models.DecimalField(
                decimal_places=0,
                default=100,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="weight",
            field=models.DecimalField(
                decimal_places=0,
                default=100,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
            ),
        ),
    ]
