# Generated by Django 5.1.6 on 2025-02-08 20:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0026_alter_serving_serving_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="nutritional_info_size",
            field=models.DecimalField(
                decimal_places=1,
                default=100,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="size",
            field=models.DecimalField(
                decimal_places=1,
                default=100,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="serving",
            name="serving_size",
            field=models.DecimalField(
                decimal_places=1,
                default=100,
                help_text="Size is the amount of units in the serving. For example, if the unit is grams and the size is 100, it means 100g. When the serving unit and the food size unit is the same, then the size of the serving is the same as the size of the food. However, when the unit of the serving is 'container' or 'serving', then the size will most certainly differ from the size, e.g.: size 1 unit container sizes 320g.",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
            ),
        ),
    ]
