# Generated by Django 5.1.6 on 2025-02-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "foods",
            "0027_alter_food_nutritional_info_size_alter_food_size_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="abv_perc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Alcohol by volume (%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="abv_perc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Alcohol by volume (%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serving",
            name="abv_perc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Alcohol by volume (%)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
