# Generated by Django 5.1.6 on 2025-02-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0028_food_abv_perc_recipeingredient_abv_perc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodproduct",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
