# Generated by Django 5.1.6 on 2025-03-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0029_foodproduct_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Fat (g)",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Fat (g)",
            ),
        ),
        migrations.AlterField(
            model_name="serving",
            name="carbs_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Carbs (g)",
            ),
        ),
        migrations.AlterField(
            model_name="serving",
            name="fat_g",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Fat (g)",
            ),
        ),
    ]
