# Generated by Django 5.2.16 on 2026-08-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0038_backfill_serving_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenFoodFactsCacheEntry",
            fields=[
                (
                    "barcode",
                    models.CharField(
                        max_length=14, primary_key=True, serialize=False
                    ),
                ),
                ("product", models.JSONField(null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpenFoodFactsRateLimit",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("request_timestamps", models.JSONField(default=list)),
            ],
        ),
    ]
