# Generated by Django 5.2.15 on 2026-08-01 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0003_alter_exercise_duration"),
        ("plans", "0032_alter_day_carbs_g_alter_day_carbs_g_goal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GarminConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(default="garmin", max_length=32),
                ),
                (
                    "provider_account_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "provider_scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="OAuth scopes granted by Garmin.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "access_token_encrypted",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "refresh_token_encrypted",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "access_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "connection_generation",
                    models.PositiveBigIntegerField(default=1),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_sync_summary",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garmin_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GarminActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_activity_id", models.CharField(max_length=255)),
                ("provider_activity_type", models.CharField(max_length=64)),
                (
                    "provider_account_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "provider_local_started_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "provider_local_started_time",
                    models.TimeField(blank=True, null=True),
                ),
                (
                    "provider_timezone_offset_minutes",
                    models.SmallIntegerField(default=0),
                ),
                ("started_at", models.DateTimeField()),
                ("kcals", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                (
                    "distance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pending_reconciliation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether day resolution is still pending.",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="garmin_activities",
                        to="plans.day",
                    ),
                ),
                (
                    "exercise",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="garmin_activity",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="garmin.garminconnection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["connection", "provider_activity_id"],
                        name="garmin_garm_connect_bd60c3_idx",
                    ),
                    models.Index(
                        fields=["day"], name="garmin_garm_day_id_2b14ce_idx"
                    ),
                    models.Index(
                        fields=["provider_account_id"],
                        name="garmin_garm_provide_6af39c_idx",
                    ),
                    models.Index(
                        fields=["connection", "pending_reconciliation"],
                        name="garmin_garm_connect_fdb28e_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "connection",
                        "provider_account_id",
                        "provider_activity_id",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="GarminOAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(default="garmin", max_length=32),
                ),
                ("state_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garmin_oauth_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "provider"],
                        name="garmin_garm_user_id_fc2eda_idx",
                    ),
                    models.Index(
                        fields=["expires_at"],
                        name="garmin_garm_expires_25d1a4_idx",
                    ),
                ],
            },
        ),
    ]
