# Generated by Django 5.2.9 on 2026-01-07 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_alter_exercise_duration"),
        ("garmin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="garmincredential",
            name="access_token",
            field=models.CharField(
                max_length=255, verbose_name="access token"
            ),
        ),
        migrations.AlterField(
            model_name="garmincredential",
            name="expires_at",
            field=models.BigIntegerField(
                help_text="Token expiration timestamp (seconds since epoch)",
                verbose_name="expires at",
            ),
        ),
        migrations.AlterField(
            model_name="garmincredential",
            name="garmin_user_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="garmin user id",
            ),
        ),
        migrations.AlterField(
            model_name="garmincredential",
            name="refresh_token",
            field=models.CharField(
                max_length=255, verbose_name="refresh token"
            ),
        ),
        migrations.AlterField(
            model_name="garmincredential",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garmin_credential",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.CreateModel(
            name="GarminActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "garmin_activity_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="garmin activity id",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="data")),
                (
                    "exercise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garmin_activity",
                        to="exercises.exercise",
                        verbose_name="exercise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
