# Generated by Django 5.2.15 on 2026-08-05 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garmin", "0002_garminconnection_authorization_placeholder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="garminconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_account_id", ""), _negated=True),
                fields=("provider", "provider_account_id"),
                name="garmin_connection_blank_provider_account_uniq",
            ),
        ),
    ]
